import { RANK_OBJECT } from './Rank.js';
import { SUIT_OBJECT } from './Suit.js';
import { Card } from './Card.js';


/////////////////////////////////
//
//
/* SECTION BELOW: this is the map for the many card objects, analagous to a deck */
//
//
/////////////////////////////////

let CARD_OBJECT = new Map<string, Card>();
CARD_OBJECT.set("THREE_OF_DIAMONDS", new Card(RANK_OBJECT.THREE, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("THREE_OF_CLUBS", new Card(RANK_OBJECT.THREE, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("THREE_OF_HEARTS", new Card(RANK_OBJECT.THREE, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("THREE_OF_SPADES", new Card(RANK_OBJECT.THREE, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("FOUR_OF_DIAMONDS", new Card(RANK_OBJECT.FOUR, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("FOUR_OF_CLUBS", new Card(RANK_OBJECT.FOUR, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("FOUR_OF_HEARTS", new Card(RANK_OBJECT.FOUR, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("FOUR_OF_SPADES", new Card(RANK_OBJECT.FOUR, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("FIVE_OF_DIAMONDS", new Card(RANK_OBJECT.FIVE, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("FIVE_OF_CLUBS", new Card(RANK_OBJECT.FIVE, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("FIVE_OF_HEARTS", new Card(RANK_OBJECT.FIVE, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("FIVE_OF_SPADES", new Card(RANK_OBJECT.FIVE, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("SIX_OF_DIAMONDS", new Card(RANK_OBJECT.SIX, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("SIX_OF_CLUBS", new Card(RANK_OBJECT.SIX, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("SIX_OF_HEARTS", new Card(RANK_OBJECT.SIX, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("SIX_OF_SPADES", new Card(RANK_OBJECT.SIX, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("SEVEN_OF_DIAMONDS", new Card(RANK_OBJECT.SEVEN, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("SEVEN_OF_CLUBS", new Card(RANK_OBJECT.SEVEN, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("SEVEN_OF_HEARTS", new Card(RANK_OBJECT.SEVEN, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("SEVEN_OF_SPADES", new Card(RANK_OBJECT.SEVEN, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("EIGHT_OF_DIAMONDS", new Card(RANK_OBJECT.EIGHT, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("EIGHT_OF_CLUBS", new Card(RANK_OBJECT.EIGHT, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("EIGHT_OF_HEARTS", new Card(RANK_OBJECT.EIGHT, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("EIGHT_OF_SPADES", new Card(RANK_OBJECT.EIGHT, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("NINE_OF_DIAMONDS", new Card(RANK_OBJECT.NINE, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("NINE_OF_CLUBS", new Card(RANK_OBJECT.NINE, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("NINE_OF_HEARTS", new Card(RANK_OBJECT.NINE, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("NINE_OF_SPADES", new Card(RANK_OBJECT.NINE, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("TEN_OF_DIAMONDS", new Card(RANK_OBJECT.TEN, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("TEN_OF_CLUBS", new Card(RANK_OBJECT.TEN, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("TEN_OF_HEARTS", new Card(RANK_OBJECT.TEN, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("TEN_OF_SPADES", new Card(RANK_OBJECT.TEN, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("JACK_OF_DIAMONDS", new Card(RANK_OBJECT.JACK, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("JACK_OF_CLUBS", new Card(RANK_OBJECT.JACK, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("JACK_OF_HEARTS", new Card(RANK_OBJECT.JACK, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("JACK_OF_SPADES", new Card(RANK_OBJECT.JACK, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("QUEENE_OF_DIAMONDS", new Card(RANK_OBJECT.QUEEN, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("QUEEN_OF_CLUBS", new Card(RANK_OBJECT.QUEEN, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("QUEEN_OF_HEARTS", new Card(RANK_OBJECT.QUEEN, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("QUEEN_OF_SPADES", new Card(RANK_OBJECT.QUEEN, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("KING_OF_DIAMONDS", new Card(RANK_OBJECT.KING, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("KING_OF_CLUBS", new Card(RANK_OBJECT.KING, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("KING_OF_HEARTS", new Card(RANK_OBJECT.KING, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("KING_OF_SPADES", new Card(RANK_OBJECT.KING, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("ACEOF_DIAMONDS", new Card(RANK_OBJECT.ACE, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("ACE_OF_CLUBS", new Card(RANK_OBJECT.ACE, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("ACE_OF_HEARTS", new Card(RANK_OBJECT.ACE, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("ACE_OF_SPADES", new Card(RANK_OBJECT.ACE, SUIT_OBJECT.SPADES));

CARD_OBJECT.set("TWO_OF_DIAMONDS", new Card(RANK_OBJECT.TWO, SUIT_OBJECT.DIAMONDS));
CARD_OBJECT.set("TWO_OF_CLUBS", new Card(RANK_OBJECT.TWO, SUIT_OBJECT.CLUBS));
CARD_OBJECT.set("TWO_OF_HEARTS", new Card(RANK_OBJECT.TWO, SUIT_OBJECT.HEARTS));
CARD_OBJECT.set("TWO_OF_SPADES", new Card(RANK_OBJECT.TWO, SUIT_OBJECT.SPADES));

export { CARD_OBJECT }
